name: Deploy to VPS

on:
  push:
    branches: [ create_portfolio ]  # ou master, selon votre branche

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/Laura29092002.github.io
          git pull
          npm install
          npm run build
